### ISSUE TITLE
能否增加多个定时器任务，每个任务独立运行🧐

### ISSUE THREAD

**Issue by TohsakaGozen** [happysnaker/mirai-plugin-HRobot#15]
**您的想法？**
自定义多个定时任务实例

**为何要这么做？**
你看，能向群友们说早安，肯定也要给群友们说晚安啦

**提供竞品链接（如果有的话）**
清晰简洁的描述。

**附加上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by happysnaker** [comment]
他似乎一直都是可以支持的？

**Comment by happysnaker** [comment]
![image](https://user-images.githubusercontent.com/73147033/192210771-a069b493-b486-4ade-a84c-e3a2ed312c47.png)
![image](https://user-images.githubusercontent.com/73147033/192210557-b461ebeb-c430-4fb6-8ea7-51b4d08c1f58.png)
只需要配置多个定时任务项即可。

**Comment by TohsakaGozen** [comment]
原理是这样，谢谢大佬嘞
