### ISSUE TITLE
你好，能请教一下如何关键字回复图片吗

### ISSUE THREAD

**Issue by d448153274** [happysnaker/mirai-plugin-HRobot#17]
**您的想法？**
你好，能请教一下如何关键字回复图片吗

**为何要这么做？**
我看介绍说可以回复图片，但是配置文档里没有介绍如何添加图片，刚玩mirai不久，很多不太懂，打扰了

**Comment by mashiro2020-10** [comment]
![image](https://user-images.githubusercontent.com/73225180/195552780-c5ae6f33-a8df-4f8e-b92b-a17bc0b25b3c.png)

**Comment by mashiro2020-10** [comment]
> **您的想法？** 你好，能请教一下如何关键字回复图片吗
> 
> **为何要这么做？** 我看介绍说可以回复图片，但是配置文档里没有介绍如何添加图片，刚玩mirai不久，很多不太懂，打扰了

我一开始也不知道，不过尝试了一下，至少在群里通过#设置关键字回复，然后把图放上去是可行的，截图看下面~

**Comment by d448153274** [comment]
> > **你的意见好不好**，能请教一下如何关键字回复图片吗
> > ****为什么**要这样做？**
> 
> 我一开始也不知道，不过尝试删除，至少在群里通过#设置关键字回复，然后把图放上去是有效果的，下面截图~

但是图片怎么放入yaml配置文件里呢，我以为是用什么命令只想某个路径的文件

**Comment by happysnaker** [comment]
> 

抱歉哈，目前还没有支持这种配置，图片必须要先上传腾讯服务器然后使用 mirai 码引用，暂不支持使用某路径或者 URL，不过你这是个很好的想法，我会考虑在下个版本加上去的。

**Comment by happysnaker** [comment]
> > > **你的意见好不好**，能请教一下如何关键字回复图片吗
> > > ****为什么**要这样做？**
> > 
> > 
> > 我一开始也不知道，不过尝试删除，至少在群里通过#设置关键字回复，然后把图放上去是有效果的，下面截图~
> 
> 但是图片怎么放入yaml配置文件里呢，我以为是用什么命令只想某个路径的文件


抱歉哈，目前还没有支持这种配置，图片必须要先上传腾讯服务器然后使用 mirai 码引用，暂不支持使用某路径或者 URL，不过你这是个很好的想法，我会考虑在下个版本加上去的。

目前想要发送图片可能只能通过命令方式........

**Comment by d448153274** [comment]
> > > > **你的意见好不好**，能请教一下如何关键字回复图片吗
> > > > ****为什么**要这样做？**
> > > 
> > > 
> > > 我一开始也不知道，不过尝试删除，至少在群里通过#设置关键字回复，然后把图放上去是有效果的，下面截图~
> > 
> > 
> > 但是图片怎么放入yaml配置文件里呢，我以为是用什么命令只想某个路径的文件
> 
> 抱歉哈，目前还没有支持这种配置，图片必须要先上传腾讯服务器然后使用 mirai 码引用，暂不支持使用某路径或者 URL，不过你这是个很好的想法，我会考虑在下个版本加上去的。
> 
> 目前想要发送图片可能只能通过命令方式........

哦哦好的，感谢解答

**Comment by happysnaker** [comment]
> **您的想法？** 你好，能请教一下如何关键字回复图片吗
> 
> **为何要这么做？** 我看介绍说可以回复图片，但是配置文档里没有介绍如何添加图片，刚玩mirai不久，很多不太懂，打扰了

目前这个功能已经在 v3.4 中实现了，可以通过特殊的语法完成这个目的，感谢提出建议。
