### ISSUE TITLE
问问，能不能自定义@后问话的回复。

### ISSUE THREAD

**Issue by sijiyingji** [happysnaker/mirai-plugin-HRobot#2]
如题，现在机器人的名字默认是菲菲，在配置文件找不到怎么改，希望把词库的修改功能加一下#瘫倒。这样子搞的没啥人设（）

**Comment by happysnaker** [comment]
恐怕不行，我这是直接调用别人 API 的（哭），不过 3.0 版本支持回复替换，可以用这种方式曲线救国
