### ISSUE TITLE
“鸡汤”功能无法使用

### ISSUE THREAD

**Issue by XinFeng114514** [happysnaker/mirai-plugin-HRobot#20]
**描述问题**
在群里使用“鸡汤”功能时，机器人发出“意外地失去了与地球上的通信...  错误原因：null”
![QQ截图20221103154639](https://user-images.githubusercontent.com/117132950/199669830-9bada66d-455e-46d7-8f06-c8db6d95d331.png)

**使用的插件版本**
出现问题所使用的插件版本是: 3.3

**使用的 mcl 版本**
出现问题所使用的 mcl 版本是: 2.12.3

**使用的操作系统是**
出现问题所使用的操作系统是: Windows 7

**错误问题截图**
![QQ图片20221103155138](https://user-images.githubusercontent.com/117132950/199670229-53a3a57d-5b5f-4bfa-a851-7b9ce18e3e16.png)

**Comment by happysnaker** [comment]
鸡汤会附加一张二次元图片，目前这个 API 失效了，已经更换了，可以更新下 v3.4，感谢指出问题

**Comment by XinFeng114514** [comment]
好的
