### ISSUE TITLE
请问是否可以加入功能开关

### ISSUE THREAD

**Issue by DanielToyama** [happysnaker/mirai-plugin-HRobot#22]
**您的想法？**
请问是否可以加入功能开关
**为何要这么做？**
有的功能没有需求，希望可以关闭。谢谢大佬

**Comment by Takeoff0518** [comment]
附议，青云客的调用经常出现逆天言论，希望提供直接关闭对话的配置项（readme写的可以关闭，但是并未找到相关配置项，只有一个配置是否需要@触发的配置项）。

**Comment by Takeoff0518** [comment]
upd: 对话~~手动~~关闭方法：

`com.happysnaker.handler.impl.GroupMessageEventHandler` 里面找到 `handleMessageEvent`，把最后一行改成 `return null;`。

```java
    @Override
    public List<MessageChain> handleMessageEvent(MessageEvent event, Context ctx) {
        String content = getPlantContent(event);
        String help1 = "帮助", help2 = "help", help3 = "菜单";
        if (help1.equals(content) || help2.equals(content) || help3.equals(content)) {
            if (!RobotConfig.menu.isEmpty()) {
                return buildMessageChainAsSingletonList(RobotConfig.menu);
            } else {
                return buildMessageChainAsSingletonList("暂未配置相关信息，请即使配置");
            }
        }
//        logError(event, StringUtil.getErrorInfoFromException(new PermissionDeniedException("权限不足")));
//        return OfUtil.ofList(replaceFaceFromContent(QingYunKeApi.getMessage(content)));
        return null;
    }
```

**Comment by DanielToyama** [comment]
> upd: 对话~手动~关闭方法：
> 
> `com.happysnaker.handler.impl.GroupMessageEventHandler` 里面找到 `handleMessageEvent`，把最后一行改成 `return null;`。
> 
> ```java
>     @Override
>     public List<MessageChain> handleMessageEvent(MessageEvent event, Context ctx) {
>         String content = getPlantContent(event);
>         String help1 = "帮助", help2 = "help", help3 = "菜单";
>         if (help1.equals(content) || help2.equals(content) || help3.equals(content)) {
>             if (!RobotConfig.menu.isEmpty()) {
>                 return buildMessageChainAsSingletonList(RobotConfig.menu);
>             } else {
>                 return buildMessageChainAsSingletonList("暂未配置相关信息，请即使配置");
>             }
>         }
> //        logError(event, StringUtil.getErrorInfoFromException(new PermissionDeniedException("权限不足")));
> //        return OfUtil.ofList(replaceFaceFromContent(QingYunKeApi.getMessage(content)));
>         return null;
>     }
> ```

草
