### ISSUE TITLE
加入随机回复

### ISSUE THREAD

**Issue by loolksama** [happysnaker/mirai-plugin-HRobot#9]
**您的想法？**
关键字回复可以有随机回复 例如 晚安
然后设置多个关键字回复之后 随机回复

**为何要这么做？**
想加入多点随机
**提供竞品链接（如果有的话）**
清晰简洁的描述。

**附加上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by happysnaker** [comment]
更新了 v3.2.1，在配置文件中以数组形式给出多个值就好了

**Comment by happysnaker** [comment]
老哥要不来一起开发吧 😂😂

**Comment by loolksama** [comment]
qq 3386881915 我才高三o3o

**Comment by happysnaker** [comment]
啊，这，嗯，好好学习天天向上

**Comment by loolksama** [comment]
谢谢你;w;

**Comment by happysnaker** [comment]
斯，你下半年高三吗，那确实得好好学习，现在大环境差，没个 985-211 简历都没人要的，加油
